### ISSUE TITLE
[ECP-9343]Undefined array key 1 in \/vendor\/magento\/framework\/View\/Layout\/Generator\/Block.php on line 212

### ISSUE THREAD

**Issue by kallard1** [Adyen/adyen-magento2-hyva#45]
Hello,

Since the installation of the module, we are encountering the following problem when the project is in production mode:

```
{"message":"Warning: Undefined array key 1 in \/vendor\/magento\/framework\/View\/Layout\/Generator\/Block.php on line 212","code":500}
```

This URI: `magewire/post/livewire/message/...` responds correctly with a 200 status if we are in `developer` mode, but in production mode, it returns a 500 error with the error mentioned above.

To reproduce:

1. Ensure you are in production mode.
2. Add a product to the cart.
3. Trigger any AJAX request (reload shipping method after entering the address, choosing the payment method) and the error appears.

I tested by removing the module, and the problem no longer occurs.

**Magento version**
2.4.7

**Plugin version**
1.0.0-rc1

**Screenshots**
![Screenshot from 2024-07-11 15-20-16](https://github.com/Adyen/adyen-magento2-hyva/assets/31655652/b154ddaa-c076-4cd5-a531-e850c9693057)

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04 LTS
- Browser: Chrome
- Version: 126.0.6478.126 (Official Build) (64-bit)

**Comment by RokPopov** [comment]
Hi @kallard1, 

I’ve tested the scenario you described in production mode using the latest official release version 1.0.0. After initiating backend calls on the checkout page (e.g., changing payment method, shipping method, and shipping address), I could not reproduce the issue. It seems this problem was specific to the release candidate version you mentioned.

Please update to the [latest version](https://github.com/Adyen/adyen-magento2-hyva/releases/tag/1.0.0) and reach out to support@adyen.com in case you encounter any issues.

Kind regards,
Rok
